pipeline {
  agent any
  tools {
    nodejs 'node-11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        bat 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        bat 'cd jenkins-tests && npm t'
      }
    }
    stage('RUN REMOTE') {
      steps {
        build wait: false, job: 'parameterized', parameters: [string(name: 'ROOT_ID', value: '$BUILD_ID')]
      }
    }
  }
}
